# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import textclassifier.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField()),
                ('comment', textclassifier.fields.TextClassificationField()),
            ],
        ),
    ]
